COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= activity_recognition.c

API_LOCATION ?= ../..

COMMON_LOCATION ?= ..

C_SRCS += \
$(API_LOCATION)/bmi2.c \
$(API_LOCATION)/bmi270_context.c \
$(COMMON_LOCATION)/common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
$(COMMON_LOCATION)/common

include $(COINES_INSTALL_PATH)/coines.mk