COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= ois_accel_gyro.c

API_LOCATION ?= ../..

COMMON_LOCATION ?= ..

C_SRCS += \
$(API_LOCATION)/bmi2.c \
$(API_LOCATION)/bmi2_ois.c \
$(COMMON_LOCATION)/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
$(COMMON_LOCATION)/common

include $(COINES_INSTALL_PATH)/coines.mk