blank_issues_enabled: false
contact_links:
  - name: Configuration and other support questions
    url: https://discord.betaflight.com/invite
    about: Ask the Betaflight community on Discord for help with wiring, setup and tuning
  - name: Hardware Issues
    url: https://github.com/betaflight/betaflight#hardware-issues
    about: Hardware problems (faults, configs, documentation, warranty) go to the manufacturer of your hardware
