import sys

if len(sys.argv) > 1:
    f = open(sys.argv[1], "r")
else:
    f = sys.stdin

mods = dict(
    (
        # MCM   FB bit-reversed
        ("00", "01"), # Black
        ("01", "00"), # Transparent
        ("10", "11"), # White
        ("11", "00")  # Transparent
    )
)

# https://www.analog.com/en/resources/design-notes/generating-custom-characters-and-graphics-by-using-the-max7456s-memory-and-ev-kit-file-formats.html
# This is the format of .mcm files for BetaFlight etc.
# each 3 bytes, first byte is left column of 4 pixels, 2nd byte is middle, 3rd byte is right
# each byte is 4 pixels as 4x 2 bits (see mods), with left to right being high to low
# so, for ease of sending buffer to fifo to screen ("wire order"), we want to reverse the order of the 4 pixels in each byte

print("/*")
print(" * This file is part of Betaflight.")
print(" *")
print(" * Betaflight is free software. You can redistribute this software")
print(" * and/or modify this software under the terms of the GNU General")
print(" * Public License as published by the Free Software Foundation,")
print(" * either version 3 of the License, or (at your option) any later")
print(" * version.")
print(" *")
print(" * Betaflight is distributed in the hope that it will be useful,")
print(" * but WITHOUT ANY WARRANTY; without even the implied warranty of")
print(" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.")
print(" *")
print(" * See the GNU General Public License for more details.")
print(" *")
print(" * You should have received a copy of the GNU General Public")
print(" * License along with this software.")
print(" *")
print(" * If not, see <http://www.gnu.org/licenses/>.")
print(" */")
print()

print("// Generated by python %s %s"%(sys.argv[0],sys.argv[1] if len(sys.argv) > 1 else ""))
print()

row = 0
header = f.readline().strip()

print("#include <stdint.h>")
print()
print("// %s font"%header)
print("uint8_t fontData[18*3*256] = {", end="") # not const to allow for overwrite in place with font data from Flash
for x in f:
    z = row % 64
    if (z >= 54):
        row += 1
        continue
    rc = z % 3
    if (rc == 0):
        if (row > 0 and z == 0):
            print()
        print("\n    ", end="")
    print("0b", end="")
    a=""
    for i in range(4):
        a += mods[x[2*i:2*(i+1)]]
    print(a[::-1], end="") # reverse order of bits in byte
    print(",", end="")
    if (rc != 2):
        print(" ", end="")
    row += 1
print("\n};")
