

typedef enum {
    DMA_NONE = 0,
    DMA_CH1_HANDLER = 1,
    DMA_CH2_HANDLER,
    DMA_CH3_HANDLER,
    DMA_CH4_HANDLER,
    DMA_CH5_HANDLER,
    DMA_CH6_HANDLER,
    DMA_CH7_HANDLER,
    DMA_CH8_HANDLER,
    DMA_CH9_HANDLER,
    DMA_CH10_HANDLER,
    DMA_CH11_HANDLER,
    DMA_CH12_HANDLER,
#ifdef RP2350
    DMA_CH13_HANDLER,
    DMA_CH14_HANDLER,
    DMA_CH15_HANDLER,
    DMA_CH16_HANDLER,
#endif
    DMA_HANDLER_END
} dmaIdentifier_e;
