// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// dshot_600 //
// --------- //

#define dshot_600_wrap_target 0
#define dshot_600_wrap 12
#define dshot_600_pio_version 0

static const uint16_t dshot_600_program_instructions[] = {
            //     .wrap_target
    0xff00, //  0: set    pins, 0                [31]
    0xb442, //  1: nop                           [20]
    0x80a0, //  2: pull   block
    0x6050, //  3: out    y, 16
    0x6041, //  4: out    y, 1
    0x006a, //  5: jmp    !y, 10
    0xfa01, //  6: set    pins, 1                [26]
    0xe900, //  7: set    pins, 0                [9]
    0x00e4, //  8: jmp    !osre, 4
    0x0000, //  9: jmp    0
    0xec01, // 10: set    pins, 1                [12]
    0xf600, // 11: set    pins, 0                [22]
    0x01e4, // 12: jmp    !osre, 4               [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_600_program = {
    .instructions = dshot_600_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = dshot_600_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_600_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_600_wrap_target, offset + dshot_600_wrap);
    return c;
}
#endif

// --------------- //
// dshot_600_bidir //
// --------------- //

#define dshot_600_bidir_wrap_target 0
#define dshot_600_bidir_wrap 31
#define dshot_600_bidir_pio_version 0

#define dshot_600_bidir_BIDIR_START 0

static const uint16_t dshot_600_bidir_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe081, //  1: set    pindirs, 1
    0x6050, //  2: out    y, 16
    0xe034, //  3: set    x, 20
    0x6041, //  4: out    y, 1
    0xe000, //  5: set    pins, 0
    0x006e, //  6: jmp    !y, 14
    0xbf42, //  7: nop                           [31]
    0xbf42, //  8: nop                           [31]
    0xb142, //  9: nop                           [17]
    0xff01, // 10: set    pins, 1                [31]
    0xa642, // 11: nop                           [6]
    0x00e4, // 12: jmp    !osre, 4
    0x0014, // 13: jmp    20
    0xbf42, // 14: nop                           [31]
    0xa642, // 15: nop                           [6]
    0xff01, // 16: set    pins, 1                [31]
    0xbf42, // 17: nop                           [31]
    0xb142, // 18: nop                           [17]
    0x00e4, // 19: jmp    !osre, 4
    0xb442, // 20: nop                           [20]
    0xe080, // 21: set    pindirs, 0
    0x20a0, // 22: wait   1 pin, 0
    0xe023, // 23: set    x, 3
    0x2020, // 24: wait   0 pin, 0
    0xe05f, // 25: set    y, 31
    0x4001, // 26: in     pins, 1
    0xaf42, // 27: nop                           [15]
    0x009a, // 28: jmp    y--, 26
    0x0059, // 29: jmp    x--, 25
    0xe081, // 30: set    pindirs, 1
    0xe001, // 31: set    pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_600_bidir_program = {
    .instructions = dshot_600_bidir_program_instructions,
    .length = 32,
    .origin = -1,
    .pio_version = dshot_600_bidir_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_600_bidir_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_600_bidir_wrap_target, offset + dshot_600_bidir_wrap);
    return c;
}
#endif

