name: Manual Target Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Firmware
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/betaflight betaflight/betaflight-build make TARGET=SPEEDYBEEF405V3
          
      - name: Upload Hex Firmware
        uses: actions/upload-artifact@v4
        with:
          name: custom-failsafe-firmware
          path: obj/*.hex
